=== Kasumi-chan18/assignment-1--principles-of-databases--cs-365--fall-2025/xml/student.dtd
<!ELEMENT students (student+)>

<!ELEMENT student (name, nickname?, email, phone?, year?, major?, status?, advisor?, dob?, admit?)>
<!ATTLIST student id CDATA #REQUIRED>

<!ELEMENT name (#PCDATA)>
<!ELEMENT nickname (#PCDATA)>
<!ELEMENT email (#PCDATA)>
<!ELEMENT phone (#PCDATA)>
<!ELEMENT year (#PCDATA)>
<!ELEMENT gpa (#PCDATA)>
<!ELEMENT major (#PCDATA)>
<!ELEMENT minor (#PCDATA)>
<!ELEMENT status (#PCDATA)>
<!ELEMENT advisor (#PCDATA)>
<!ELEMENT dob (#PCDATA)>
<!ELEMENT admit (#PCDATA)>

=== Kasumi-chan18/assignment-1--principles-of-databases--cs-365--fall-2025/xml/index.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/css" href="style.css"?>
<!DOCTYPE students SYSTEM "student.dtd">
<students>
  <student id="1234567">
    <name>Gordon Matthew Sumner</name>
    <nickname>“Sting”</nickname>
    <email>&lt;sting@thepolice.com&gt;</email>
    <phone>212.123.4567</phone>
    <year>first year</year>
    <gpa>4.0</gpa>
    <major>Music</major>
    <minor>English</minor>
    <status>full-time</status>
    <advisor>Andy Summers</advisor>
    <dob>08-25-1969</dob>
    <admit>05-01-1973</admit>
  </student>

  <student id="4567890">
    <name>Kim Thayil</name>
    <nickname></nickname>
    <email>&lt;kim@soundgarden.com&gt;</email>
    <phone>206.123.4567</phone>
    <year>second year</year>
    <gpa>3.0</gpa>
    <major>Philosophy</major>
    <minor>Music</minor>
    <status>full-time</status>
    <advisor>Chris Cornell</advisor>
    <dob>08-25-1978</dob>
    <admit>05-01-1982</admit>
  </student>

  <student id="8302438">
    <name>Saul Hudson</name>
    <nickname>“Slash”</nickname>
    <email>&lt;slash@gnr.com&gt;</email>
    <phone>213.456.8392</phone>
    <year>fourth year</year>
    <gpa>2.0</gpa>
    <major>Music</major>
    <minor>Criminal Justice</minor>
    <status>part-time</status>
    <advisor>Axl Rose</advisor>
    <dob>08-25-1983</dob>
    <admit>05-01-1987</admit>
  </student>

  <student id="2983928">
    <name>Emily Kokal</name>
    <nickname></nickname>
    <email>&lt;emily@warpaint.com&gt;</email>
    <phone>213.123.7654</phone>
    <year>third year</year>
    <gpa>3.8</gpa>
    <major>Political Science</major>
    <minor>Law</minor>
    <status>full-time</status>
    <advisor>Jenny Lee Lindberg</advisor>
    <dob>08-25-1998</dob>
    <admit>05-01-2002</admit>
  </student>

  <student id="7645726">
    <name>Mike Inez</name>
    <nickname></nickname>
    <email>&lt;mike@aic.com&gt;</email>
    <phone>213.444.3323</phone>
    <year>second year</year>
    <gpa>4.0</gpa>
    <major>Business Management</major>
    <minor>Math</minor>
    <status>full-time</status>
    <advisor>Jerry Cantrell</advisor>
    <dob>08-25-1984</dob>
    <admit>05-01-1988</admit>
  </student>
</students>
